### ISSUE TITLE
Error:(4, 0) Cause: de/felixschulze/gradle/SpoonPlugin : Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by kannanloganathan** [x2on/gradle-spoon-plugin#11]
Whenever i try to do a gradle sync, i have been getting this error. 
Error:(4, 0) Cause: de/felixschulze/gradle/SpoonPlugin : Unsupported major.minor version 51.0

I am using Android Studio V 1.0.9. i upgraded to 1.1.0, but still does not help..

But still i am able to use spoon when i try using the command line. this is what i have in my build.gradle.

    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.0'
        classpath 'org.robolectric:robolectric-gradle-plugin:0.14.+'
        classpath 'com.jakewharton.hugo:hugo-plugin:1.1.0'
       }

apply plugin: 'com.android.application'
apply plugin: 'robolectric'
apply plugin: 'hugo'
apply plugin: 'de.felixschulze.gradle.spoon'

Any help will be appreciated

**Comment by x2on** [comment]
Hi, sounds like an issue with your JDK.

Which version do you have installed?

see http://stackoverflow.com/questions/10382929/unsupported-major-minor-version-51-0

**Comment by x2on** [comment]
Im closing this during inactivity. Please feel free to reopen if the problem is not solved.
