### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by ligi** [x2on/gradle-spoon-plugin#14]
The new plugin 2.6 works nice with 1.5.0 on the command-line - unfortunately when syncing with AS I get the following:

      Error:(19, 0) Cause: de/felixschulze/gradle/SpoonPlugin : Unsupported major.minor version 52.0

**Comment by x2on** [comment]
Ah i hate this error. This is because i compiled the plugin with Java 8... I will make a fix.

**Comment by x2on** [comment]
Should be fixed with 2.6.1 (04ec600)

**Comment by ligi** [comment]
:+1:
