### ISSUE TITLE
Can you add the option instrumentationArgs ?

### ISSUE THREAD

**Issue by rafaelaazevedo** [x2on/gradle-spoon-plugin#15]
I would like to use instrumentation arguments, because I am using cucumber on my tests. Is possible add this option on spoon task ? Arguments to pass to the Instrumentation Runner. This can be used multiple times for multiple entries. Usage: --instrumentationArgs <NAME>=<VALUE>.

I used to pass this option like:
instrumentationArgs = ["cucumberOptions=" + "'${project.cucumberOptions}'"]

Thank you !

**Comment by x2on** [comment]
Will be available with the next release!

**Comment by rafaelaazevedo** [comment]
Thank you :+1:
