### ISSUE TITLE
[Windows] Can't run tests on more than one device parallely

### ISSUE THREAD

**Issue by polok** [x2on/gradle-spoon-plugin#2]
On one device the tests are running but if I connect for instance two emulators (I am using genymotion emulators) the test are not running. In logs I get message like:

```
[SR.runTests] Executing instrumentation suite on 2 device(s).
```

But almost immediately after this message the build is stopped. I went to report directory and after clicking 'index.html' I can see such message

```
C:\PATH_TO_MY_PROJECT\build\spoon-output\Test\work\192.168.56.102:5555\execution.json (The filename, directory name, or volume label syntax is incorrect)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.(FileOutputStream.java:212)
    at java.io.FileOutputStream.(FileOutputStream.java:165)
    at java.io.FileWriter.(FileWriter.java:90)
    at com.squareup.spoon.SpoonDeviceRunner.runInNewProcess(SpoonDeviceRunner.java:97)
    at com.squareup.spoon.SpoonRunner$1.run(SpoonRunner.java:128)
    at java.lang.Thread.run(Thread.java:724)

```

Seems that this is connected with windows and issue - https://github.com/x2on/gradle-spoon-plugin/issues/1

**Comment by itsmortoncornelius** [comment]
I have the same problem. Any news about it?

**Comment by HarishReddy93** [comment]
Hi All,
         I am new to the Genymotion can we run multiple instances in multiple AVD's(Android virtual device) simultanously in Genymotion.

if possible then give me a detail description about that even if you have any videos related to that please share me without fail.

Thanks in Advance,

**Comment by pernilla** [comment]
Any news? I can't either run on multiple devices. Running with 

  androidTestCompile 'com.squareup.spoon:spoon-client:1.2.0'
  classpath 'com.stanfy.spoon:spoon-gradle-plugin:1.0.3'

Logfile attached with our problem. 

[log.txt](https://github.com/x2on/gradle-spoon-plugin/files/38917/log.txt)

**Comment by rafaelaazevedo** [comment]
I am having the same problem after updated to 1.3.1 spoon
